<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

<!-- Umbraco packages -->
<PropertyGroup>
    <UmbracoCmsPackageVersion>[18.0.0-beta1, 18)</UmbracoCmsPackageVersion>
</PropertyGroup>
  <ItemGroup>
      <!-- PDF -->
      <PackageVersion Include="PdfPig" Version="0.1.12" />
      
      <!-- Test -->
      <PackageVersion Include="Moq" Version="4.18.4" />
      <PackageVersion Include="NUnit" Version="3.13.3" />
      <PackageVersion Include="NUnit3TestAdapter" Version="3.16.1" />
      <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
      
      <!-- Umbraco -->
      <PackageVersion Include="Umbraco.Cms.Web.Common" Version="$(UmbracoCmsPackageVersion)" />
      <PackageVersion Include="Umbraco.Cms" Version="$(UmbracoCmsPackageVersion)" />
      <PackageVersion Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="$(UmbracoCmsPackageVersion)" />
  </ItemGroup>
</Project>
